spring.application.name=postal-code-service

spring.datasource.url=jdbc:h2:mem:postalcodedb;
#DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

server.servlet.context-path=
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8082

logging.level.com.postalcode=DEBUG
logging.level.org.springframework.web=INFO

restcountries.api.base-url=https://restcountries.com/v3.1/alpha/

management.endpoints.web.exposure.include=mappings,health